#!/bin/python3

import math
import os
import random
import re
import sys
from collections import defaultdict
#
# There is a large pile of socks that must be paired by color.
# Given an array of integers representing the color of each sock, 
# determine how many pairs of socks with matching colors there are.
# 
# Complete the 'sockMerchant' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY ar
#

def sockMerchant(n, ar):
    # Write your code here
    pairs = 0
    colors = defaultdict(int)
    for i,color in enumerate(ar):
        if color not in colors:
            colors[color]=1
        else:
            colors[color]+=1
    if len(colors) == n-1:
        pairs = 1
    elif len(colors) < n-1:
        for i, color in enumerate(colors):
            pair_color = int(colors[color] / 2)
            if pair_color > 0:
                pairs += pair_color
    return pairs
            
            
    
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    ar = list(map(int, input().rstrip().split()))

    result = sockMerchant(n, ar)

    fptr.write(str(result) + '\n')

    fptr.close()
